* Org-phabricator

  Phabricator integration with Emacs org-mode.

  Currently, includes:

  - Importing tasks
  - Exporting org files to remarkup

* Installation

  Clone the repository somewhere, for example into your =.emacs.d/=
  and add the repo directory into your =load-path=.

  #+NAME: .emacs
  #+begin_src emacs-lisp :exports code
    ;; ...
    (add-to-list 'load-path "~/.emacs.d/org-phabricator")
    (require 'org-ph)
    ;; ...
  #+end_src

* Usage

** Exporting

   To export a buffer do =M-x org-export-dispatch r R=. This will
   export the code block

   The current version gives a very limited org-export functionality.

   - [X] Headings
     - [X] ToDo's
   - [x] Hyperlinks
   - [x] Lists
   - [x] Code blocks
   - [x] Tables
   - [x] Images
   - [x] Files

** Fetching new tasks

   A command =org-ph-fetch-see-new-tasks= will pop up a
   =*Phabricator*= buffer with all the taks assigned to you.

   Every task will contain the Phabricator ID in the =PHABRICATOR_ID=
   property. If a task with the same ID exists among your agenda
   files, it won't appear in the =org-ph-fetch-see-new-tasks= output.

   Also, every exported task will container a description from
   Phabricator in the =PHABRICATOR_DESCRIPTION= property.

** Exporting files
   On the file link execute =org-ph-upload-file=. =#+attr_remarkup:
   :id FXXXX= will appear on success. On export links with such an
   attribute will be replaced with their inline id: ={FXXXX}=.
